### ISSUE TITLE
how do i start the bot 

### ISSUE THREAD

**Issue by Duui3111** [theADAMJR/Bot3PG#1]
how do i start the bot

**Comment by theADAMJR** [comment]
Make sure `Lavalink.jar` is running -> `cd dist/Lavalink && java -jar Lavalink.jar`.
Also make sure `mongod` is running.
Then type `dotnet run` or `F5` with VSCode.

**Comment by theADAMJR** [comment]
Support for running the bot is being worked on (dashboard does not work properly yet and may be fixed at a later date). Updated `README.md` to be more helpful.

**Comment by Duui3111** [comment]
The dashboard never loads

**Comment by theADAMJR** [comment]
It is not yet complete.
